name: Sync to Hugging Face Spaces

on:
  push:
    branches: [ main ] # Change to your default branch if it is not main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.hf_write_token}}
        run: |
          git remote add hf https://SandeepSeesaE:$HF_TOKEN@huggingface.co/spaces/SandeepSeesa/promptea-server
          git push --force hf main
